// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type AssetResponse struct {
	Info
}

type ChattingResponse struct {
	Info
	Tips
}

type ChattingUploadRequest struct {
	File string `form:"file,optional"`
}

type Info struct {
	Information string `json:"information"`
}

type LogResponse struct {
	Info
	Logs []string `json:"logs"`
}

type LoginGETResponse struct {
	Info
	Tips
}

type LoginPOSTResponse struct {
	Info
	Token string `json:"token"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type OriginResponse struct {
	Info
}

type PingResponse struct {
	Info
	Tips
}

type Response struct {
	Code    int64       `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type Tips struct {
	Tips string `json:"tips"`
}

type WorkResponse struct {
	Info
}
