// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	private "muxi-empolyment/internal/handler/private"
	public "muxi-empolyment/internal/handler/public"
	"muxi-empolyment/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取图片
				Method:  http.MethodGet,
				Path:    "/asset/:imageId",
				Handler: private.AssetHandler(serverCtx),
			},
			{
				// 聊天
				Method:  http.MethodGet,
				Path:    "/chatting/:npcName",
				Handler: private.ChattingHandler(serverCtx),
			},
			{
				// 上传图片
				Method:  http.MethodPost,
				Path:    "/chatting/:npcName",
				Handler: private.ChattingUploadHandler(serverCtx),
			},
			{
				// 最初
				Method:  http.MethodGet,
				Path:    "/origin",
				Handler: private.OriginHandler(serverCtx),
			},
			{
				// Ping
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: private.PingHandler(serverCtx),
			},
			{
				// 工作
				Method:  http.MethodGet,
				Path:    "/work",
				Handler: private.WorkHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取日志
				Method:  http.MethodGet,
				Path:    "/debug/log",
				Handler: public.LogHandler(serverCtx),
			},
			{
				// 登录
				Method:  http.MethodGet,
				Path:    "/login",
				Handler: public.LoginGetHandler(serverCtx),
			},
			{
				// 登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: public.LoginPostHandler(serverCtx),
			},
			{
				// 开始
				Method:  http.MethodGet,
				Path:    "/start",
				Handler: public.StartHandler(serverCtx),
			},
		},
	)
}
